"""rename_model_name_to_model_id_and_change_message_model_id_type

Revision ID: 43b943c73c86
Revises: 55583d348de6
Create Date: 2025-05-10 01:40:00.264792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.schemas.enums import AIModelId  # Import the Python Enum for its values


# revision identifiers, used by Alembic.
revision: str = "43b943c73c86"
down_revision: Union[str, None] = (
    "55583d348de6"  # Please ensure this matches your actual previous migration ID
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the shared Enum type by its name as used in the database.
# It's assumed that 'aimodelid_enum' was created by a previous migration.
# We create a sa.Enum object to reference it in alter_column.
aimodelid_enum_type = sa.Enum(*[e.value for e in AIModelId], name="aimodelid_enum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Table: messages
    # Change 'model_name' (String) to 'model_id' (Enum 'aimodelid_enum')
    op.alter_column(
        "messages",
        "model_name",
        new_column_name="model_id",
        type_=aimodelid_enum_type,
        existing_type=sa.String(),
        postgresql_using="model_name::text::aimodelid_enum",
    )

    # Table: token_limits
    # Rename 'model_name' to 'model_id'. Type is already 'aimodelid_enum'.
    # Also, update the unique constraint.
    op.drop_constraint("_user_model_period_uc", "token_limits", type_="unique")
    op.alter_column(
        "token_limits",
        "model_name",
        new_column_name="model_id",
        existing_type=aimodelid_enum_type,
    )  # Type is already this enum
    op.create_unique_constraint(
        "_user_model_period_uc",
        "token_limits",
        ["user_id", "model_id", "period_unit", "period_value"],
    )

    # Table: token_usage
    # Rename 'model_name' (String) to 'model_id' (String). Type does not change.
    op.alter_column(
        "token_usage",
        "model_name",
        new_column_name="model_id",
        existing_type=sa.String(length=255),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Table: token_usage
    # Rename 'model_id' back to 'model_name'.
    op.alter_column(
        "token_usage",
        "model_id",
        new_column_name="model_name",
        existing_type=sa.String(length=255),
    )

    # Table: token_limits
    # Rename 'model_id' back to 'model_name'. Update unique constraint.
    op.drop_constraint("_user_model_period_uc", "token_limits", type_="unique")
    op.alter_column(
        "token_limits",
        "model_id",
        new_column_name="model_name",
        existing_type=aimodelid_enum_type,
    )
    op.create_unique_constraint(
        "_user_model_period_uc",
        "token_limits",
        ["user_id", "model_name", "period_unit", "period_value"],
    )

    # Table: messages
    # Change 'model_id' (Enum) back to 'model_name' (String).
    op.alter_column(
        "messages",
        "model_id",
        new_column_name="model_name",
        type_=sa.String(),  # Change type back to String
        existing_type=aimodelid_enum_type,
        postgresql_using="model_id::text",
    )  # Cast enum back to text/string
    # ### end Alembic commands ###
