"""change_token_limit_model_name_to_enum_type

Revision ID: 55583d348de6
Revises: b680bad88cbb
Create Date: 2025-05-10 01:26:49.540913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.schemas.enums import AIModelId, MetricType, PeriodUnit

# revision identifiers, used by Alembic.
revision: str = "55583d348de6"
down_revision: Union[str, None] = "b680bad88cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define PostgreSQL ENUM types using the Python Enums
# These will create ENUM types with labels like 'qwen3:8b', 'tokens', 'minute'
aimodelid_enum_pg = postgresql.ENUM(AIModelId, name="aimodelid_enum", create_type=False)
metrictype_new_enum_pg = postgresql.ENUM(
    MetricType, name="metrictype_enum", create_type=False
)
periodunit_new_enum_pg = postgresql.ENUM(
    PeriodUnit, name="periodunit_enum", create_type=False
)

# Define the old ENUM types based on Alembic's autogenerate output for downgrade
# model_name was VARCHAR, so no old enum for it.
old_metrictype_pg = postgresql.ENUM("TOKENS", name="metrictype", create_type=False)
old_periodunit_pg = postgresql.ENUM(
    "MINUTE", "HOUR", "DAY", "MONTH", name="periodunit", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # Create the new ENUM types in the database before altering columns
    aimodelid_enum_pg.create(op.get_bind(), checkfirst=True)
    metrictype_new_enum_pg.create(op.get_bind(), checkfirst=True)
    periodunit_new_enum_pg.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "token_limits",
        "model_name",
        existing_type=sa.VARCHAR(length=255),
        type_=aimodelid_enum_pg,  # Use the defined PG Enum object
        existing_nullable=False,
        postgresql_using=f"model_name::text::{aimodelid_enum_pg.name}",  # Add USING clause for casting
    )
    op.alter_column(
        "token_limits",
        "metric_type",
        existing_type=old_metrictype_pg,  # Type as it was before this migration
        type_=metrictype_new_enum_pg,  # New Enum type
        existing_nullable=False,
        postgresql_using=f"metric_type::text::{metrictype_new_enum_pg.name}",
    )
    op.alter_column(
        "token_limits",
        "period_unit",
        existing_type=old_periodunit_pg,  # Type as it was before this migration
        type_=periodunit_new_enum_pg,  # New Enum type
        existing_nullable=False,
        postgresql_using=f"period_unit::text::{periodunit_new_enum_pg.name}",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "token_limits",
        "period_unit",
        existing_type=periodunit_new_enum_pg,
        type_=old_periodunit_pg,  # Revert to the actual old enum type
        existing_nullable=False,
        postgresql_using=f"period_unit::text::{old_periodunit_pg.name}",
    )
    op.alter_column(
        "token_limits",
        "metric_type",
        existing_type=metrictype_new_enum_pg,
        type_=old_metrictype_pg,  # Revert to the actual old enum type
        existing_nullable=False,
        postgresql_using=f"metric_type::text::{old_metrictype_pg.name}",
    )
    op.alter_column(
        "token_limits",
        "model_name",
        existing_type=aimodelid_enum_pg,
        type_=sa.VARCHAR(length=255),  # Revert to VARCHAR
        existing_nullable=False,
        postgresql_using="model_name::text",  # Cast ENUM back to text/VARCHAR
    )
    # ### end Alembic commands ###

    # Drop the ENUM types created in the upgrade function
    aimodelid_enum_pg.drop(op.get_bind(), checkfirst=True)
    metrictype_new_enum_pg.drop(op.get_bind(), checkfirst=True)
    periodunit_new_enum_pg.drop(op.get_bind(), checkfirst=True)
