"""add default value for is_admin

Revision ID: 637f3b560cdd
Revises: initial
Create Date: 2025-04-11 04:55:43.068874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "637f3b560cdd"
down_revision: Union[str, None] = "initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "is_admin",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        nullable=True,
    )
    # ### end Alembic commands ###
