"""fix_reset_token_expires_at_type_to_datetime

Revision ID: 69eb925ebbf5
Revises: cc12785e15bb
Create Date: 2025-06-24 13:05:45.545424

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "69eb925ebbf5"
down_revision: Union[str, None] = "cc12785e15bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        "chat_sessions_user_id_fkey", "chat_sessions", type_="foreignkey"
    )
    op.create_foreign_key(None, "chat_sessions", "users", ["user_id"], ["id"])
    op.alter_column(
        "messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint("messages_session_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(None, "messages", "chat_sessions", ["session_id"], ["id"])
    op.drop_constraint("token_limits_user_id_fkey", "token_limits", type_="foreignkey")
    op.create_foreign_key(None, "token_limits", "users", ["user_id"], ["id"])
    op.drop_constraint("token_usage_user_id_fkey", "token_usage", type_="foreignkey")
    op.drop_constraint("token_usage_session_id_fkey", "token_usage", type_="foreignkey")
    op.create_foreign_key(None, "token_usage", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "token_usage", "chat_sessions", ["session_id"], ["id"])
    # reset_token_expires_atをVARCHARからTIMESTAMP WITH TIME ZONEに変換
    # PostgreSQLでは明示的なUSING句が必要（既存データはISO形式の文字列）
    op.execute(
        """
        ALTER TABLE users 
        ALTER COLUMN reset_token_expires_at 
        TYPE TIMESTAMP WITH TIME ZONE 
        USING CASE 
            WHEN reset_token_expires_at IS NULL OR reset_token_expires_at = '' THEN NULL
            ELSE reset_token_expires_at::timestamp with time zone
        END
    """
    )
    op.drop_index("ix_users_reset_token_expires_at", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_users_reset_token_expires_at",
        "users",
        ["reset_token_expires_at"],
        unique=False,
    )
    # TIMESTAMP WITH TIME ZONEからVARCHARに戻す（downgrade）
    op.execute(
        """
        ALTER TABLE users 
        ALTER COLUMN reset_token_expires_at 
        TYPE VARCHAR 
        USING reset_token_expires_at::text
    """
    )
    op.drop_constraint(None, "token_usage", type_="foreignkey")
    op.drop_constraint(None, "token_usage", type_="foreignkey")
    op.create_foreign_key(
        "token_usage_session_id_fkey",
        "token_usage",
        "chat_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "token_usage_user_id_fkey",
        "token_usage",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "token_limits", type_="foreignkey")
    op.create_foreign_key(
        "token_limits_user_id_fkey",
        "token_limits",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_session_id_fkey",
        "messages",
        "chat_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "chat_sessions", type_="foreignkey")
    op.create_foreign_key(
        "chat_sessions_user_id_fkey",
        "chat_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "chat_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
