"""simplify_token_limits

Revision ID: a4138a44af46
Revises: f441fa3543fc
Create Date: 2025-05-06 08:42:16.669463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4138a44af46'
down_revision: Union[str, None] = 'f441fa3543fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_limits', 'model_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('token_limits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('_user_model_period_uc', 'token_limits', ['user_id', 'model_name', 'period_unit', 'period_value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_model_period_uc', 'token_limits', type_='unique')
    op.alter_column('token_limits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('token_limits', 'model_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
