"""add_token_limits_relation_to_user_and_token_limit_models

Revision ID: b680bad88cbb
Revises: a4138a44af46
Create Date: 2025-05-06 09:05:12.716147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b680bad88cbb'
down_revision: Union[str, None] = 'a4138a44af46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
