"""fix_token_usage_session_cascade_delete

Revision ID: cc12785e15bb
Revises: ddb6fc93d72b
Create Date: 2025-06-22 09:54:23.946657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc12785e15bb'
down_revision: Union[str, None] = 'ddb6fc93d72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 既存のCASCADE制約を維持し、token_usageのsession_id制約を追加
    
    # token_usage テーブルの session_id 外部キー制約を追加（CASCADE DELETE付き）
    op.drop_constraint('token_usage_session_id_fkey', 'token_usage', type_='foreignkey')
    op.create_foreign_key(
        'token_usage_session_id_fkey', 'token_usage', 'chat_sessions', 
        ['session_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # token_usage の session_id 外部キー制約を元に戻す（CASCADE DELETEなし）
    op.drop_constraint('token_usage_session_id_fkey', 'token_usage', type_='foreignkey')
    op.create_foreign_key(
        'token_usage_session_id_fkey', 'token_usage', 'chat_sessions', 
        ['session_id'], ['id']
    )
    # ### end Alembic commands ###
