"""Rename token usage fields to prompt_tokens and completion_tokens

Revision ID: d6826bca0be3
Revises: dcb93fbca40b
Create Date: 2025-04-29 09:22:36.850942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d6826bca0be3"
down_revision: Union[str, None] = "dcb93fbca40b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("token_usage", "input_tokens", new_column_name="prompt_tokens")
    op.alter_column("token_usage", "output_tokens", new_column_name="completion_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("token_usage", "prompt_tokens", new_column_name="input_tokens")
    op.alter_column("token_usage", "completion_tokens", new_column_name="output_tokens")
    # ### end Alembic commands ###
