"""Add token usage and limit tables

Revision ID: dcb93fbca40b
Revises: d2f8a1b3e621
Create Date: 2025-04-29 08:25:27.855364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import enum

# revision identifiers, used by Alembic.
revision: str = "dcb93fbca40b"
down_revision: Union[str, None] = "d2f8a1b3e621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum定義を追加 (token_limit.pyからコピー)
class LimitType(str, enum.Enum):
    TOKENS_PER_MINUTE = "tokens_per_minute"
    TOKENS_PER_HOUR = "tokens_per_hour"
    TOKENS_PER_DAY = "tokens_per_day"
    TOKENS_PER_MONTH = "tokens_per_month"
    REQUESTS_PER_MINUTE = "requests_per_minute"
    REQUESTS_PER_HOUR = "requests_per_hour"
    REQUESTS_PER_DAY = "requests_per_day"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("limit_type", sa.Enum(LimitType, name="limittype"), nullable=False),
        sa.Column("limit_value", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_limits_id"), "token_limits", ["id"], unique=False)
    op.create_index(
        op.f("ix_token_limits_model_name"), "token_limits", ["model_name"], unique=False
    )
    op.create_index(
        op.f("ix_token_limits_user_id"), "token_limits", ["user_id"], unique=False
    )

    op.create_table(
        "token_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_usage_id"), "token_usage", ["id"], unique=False)
    op.create_index(
        op.f("ix_token_usage_model_name"), "token_usage", ["model_name"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_session_id"), "token_usage", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_timestamp"), "token_usage", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_user_id"), "token_usage", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_usage_user_id"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_timestamp"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_session_id"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_model_name"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_id"), table_name="token_usage")
    op.drop_table("token_usage")
    op.drop_index(op.f("ix_token_limits_user_id"), table_name="token_limits")
    op.drop_index(op.f("ix_token_limits_model_name"), table_name="token_limits")
    op.drop_index(op.f("ix_token_limits_id"), table_name="token_limits")
    op.drop_table("token_limits")
    sa.Enum(LimitType, name="limittype").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
