"""add_cascade_delete_relationships_for_user_deletion

Revision ID: ddb6fc93d72b
Revises: 43b943c73c86
Create Date: 2025-06-22 09:43:50.829269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddb6fc93d72b"
down_revision: Union[str, None] = "43b943c73c86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 外部キー制約を削除して、CASCADE DELETEを追加して再作成

    # chat_sessions テーブルの外部キー制約を更新
    op.drop_constraint(
        "chat_sessions_user_id_fkey", "chat_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        "chat_sessions_user_id_fkey",
        "chat_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # token_limits テーブルの外部キー制約を更新
    op.drop_constraint("token_limits_user_id_fkey", "token_limits", type_="foreignkey")
    op.create_foreign_key(
        "token_limits_user_id_fkey",
        "token_limits",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # token_usage テーブルの外部キー制約を更新
    op.drop_constraint("token_usage_user_id_fkey", "token_usage", type_="foreignkey")
    op.create_foreign_key(
        "token_usage_user_id_fkey",
        "token_usage",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # messages テーブルの外部キー制約も更新（chat_sessionが削除されたときに関連するメッセージも削除）
    op.drop_constraint("messages_session_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_session_id_fkey",
        "messages",
        "chat_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # カスケード削除を削除して、元の外部キー制約に戻す

    # messages テーブルの外部キー制約を元に戻す
    op.drop_constraint("messages_session_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_session_id_fkey", "messages", "chat_sessions", ["session_id"], ["id"]
    )

    # token_usage テーブルの外部キー制約を元に戻す
    op.drop_constraint("token_usage_user_id_fkey", "token_usage", type_="foreignkey")
    op.create_foreign_key(
        "token_usage_user_id_fkey", "token_usage", "users", ["user_id"], ["id"]
    )

    # token_limits テーブルの外部キー制約を元に戻す
    op.drop_constraint("token_limits_user_id_fkey", "token_limits", type_="foreignkey")
    op.create_foreign_key(
        "token_limits_user_id_fkey", "token_limits", "users", ["user_id"], ["id"]
    )

    # chat_sessions テーブルの外部キー制約を元に戻す
    op.drop_constraint(
        "chat_sessions_user_id_fkey", "chat_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        "chat_sessions_user_id_fkey", "chat_sessions", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
