"""Add email verification fields

Revision ID: f5bba83acca9
Revises:
Create Date: 2025-04-08 11:31:15.974848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5bba83acca9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    この関数は、メール認証とパスワードリセット機能をサポートするために必要なカラムを
    usersテーブルに追加します。これらの変更により、以下の機能が有効になります：

    1. ユーザー登録時のメールアドレス確認による本人確認
    2. パスワードを忘れたユーザーのための安全なパスワードリセットプロセス
    3. セキュリティのための検証トークンと有効期限の保存

    各カラムは認証フローにおいて特定の目的を果たします：
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # ユーザーのメールアドレスが確認済みかどうかを追跡するフラグ
    # デフォルトはFalseで、新規ユーザーは完全なアクセス権を得る前にメール確認が必要
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), default=False))

    # ユーザーのアカウント確認のためにメールで送信されるトークン
    # これは、安全な検証キーとして機能する一意のランダム生成文字列
    op.add_column("users", sa.Column("verification_token", sa.String(), nullable=True))

    # セキュリティを強化するための検証トークンの有効期限タイムスタンプ
    # この時間を過ぎるとトークンは無効になり、ユーザーは新しいトークンを要求する必要がある
    op.add_column(
        "users",
        sa.Column(
            "verification_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )

    # パスワードリセット機能のためのトークン
    # ユーザーがパスワードリセットを要求したときに生成される
    op.add_column("users", sa.Column("reset_token", sa.String(), nullable=True))

    # パスワードリセットトークンの有効期限タイムスタンプ
    # リセットリンクが無期限に使用できないようにする
    op.add_column(
        "users",
        sa.Column("reset_token_expires_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 検証トークンにインデックスを作成してクエリを高速化
    # トークンによるユーザーのメール確認時のパフォーマンスを向上
    op.create_index(
        op.f("ix_users_verification_token"),
        "users",
        ["verification_token"],
        unique=False,
    )

    # リセットトークンにインデックスを作成してクエリを高速化
    # パスワードリセットリクエスト処理時のパフォーマンスを向上
    op.create_index(
        op.f("ix_users_reset_token"), "users", ["reset_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    この関数は、upgrade関数で行われた変更を元に戻します：
    1. 検証トークンとリセットトークン用に作成されたインデックスを削除
    2. メール認証とパスワードリセットに関連するすべてのカラムを削除

    これは、メール認証が実装される前の状態にデータベーススキーマを戻す必要がある場合に必要です。
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # 参照しているカラムを削除する前に、まずインデックスを削除
    op.drop_index(op.f("ix_users_reset_token"), table_name="users")
    op.drop_index(op.f("ix_users_verification_token"), table_name="users")

    # 作成順序とほぼ逆の順序でカラムを削除
    op.drop_column("users", "reset_token_expires_at")
    op.drop_column("users", "reset_token")
    op.drop_column("users", "verification_token_expires_at")
    op.drop_column("users", "verification_token")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
